name: build-linux

on:
  push:
  pull_request:

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup premake
      uses: abel0b/setup-premake@v2
      with:
        version: "5.0.0-beta1"

    - name: install-deps
      run: sudo apt update && sudo apt  -y install libsdl2-dev

    - name: Build
      run: premake5 gmake2 && make -C build config=debug
