name: build

on:
  push:
  pull_request:

jobs:
  windows-msys2-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: base-devel
          pacboy: >-
            toolchain:x premake:x SDL2:x

      - name: CI-Build
        run: ./build.sh
