name: build

on:
  push:
  pull_request:

jobs:
  windows-msys2-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          run: ./install_dep_for_windowsmsys2_and_arch_linux.sh
      - name: CI-Build
        run: |
          set MSYSTEM=MINGW64
          msys2 -c './build.sh'